### ISSUE TITLE
Prefer immutable objects in Java

### ISSUE THREAD

**Issue by mpmenne** [dceu/mario#2]
Your `Pyramid` class looks good.  You used a standard convention in Java to create getters and setters for each attribute.  This is a best practice and is referred to as a "Java Bean".

Another best practice is to make objects immutable.  When you pass the height in via the constructor, you can delete the setter to make the object immutable.  Immutable objects are always preferred to mutable objects because their state is easier to reason about (they only have one state!).  When you're done you can throw immutable object away and make another.

Cheers,

**Comment by dceu** [comment]
~ Removed setter for my Pyramid class, and refactored the Factory to use the Pyramid(int height) constructor. Definitely more concise.
