### ISSUE TITLE
Avoid using `static`

### ISSUE THREAD

**Issue by mpmenne** [dceu/mario#3]
It looks like both of your printer classes are using a static method.

In general, static methods should be avoided in Java for several reasons:
1.  They are much more difficult to write unit tests against (you can't do dependency injection or mocking as easily)

2.  They risk having concurrency problems.  There could be variables shared across threads.  

Here's an article that explains more:
http://www.java67.com/2014/10/difference-between-static-and-non-static-method-java-programming.html

**Comment by dceu** [comment]
Refactored both printers with singleton constructors, which I instantiate per user choice in the PyramidFactory. Not sure if this was the solution you were looking for?
